[2017-12-04 15:48:15,109] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:48:15,109] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:48:15,111] I Program end
[2017-12-04 15:48:16,913] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:48:16,914] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:48:16,914] I Program end
[2017-12-04 15:56:57,822] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:56:57,822] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 185, in <module>
    main()
  File "log_analyzer.py", line 171, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:57:19,507] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:57:19,508] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 185, in <module>
    main()
  File "log_analyzer.py", line 171, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:57:42,357] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:57:42,358] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 185, in <module>
    main()
  File "log_analyzer.py", line 171, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:17,168] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:17,168] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:18,675] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:18,676] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:46,705] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:46,705] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:47,637] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:47,637] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:48,210] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:48,210] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:58:48,808] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:58:48,809] E list index out of range
Traceback (most recent call last):
  File "log_analyzer.py", line 187, in <module>
    main()
  File "log_analyzer.py", line 173, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 87, in find_last_log_file_path
    return list_of_nginx_ui_log[-1]
IndexError: list index out of range
[2017-12-04 15:59:16,438] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:59:16,439] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:59:16,441] I Program end
[2017-12-04 15:59:32,048] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:59:32,049] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:59:32,049] I Program end
[2017-12-04 15:59:33,678] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:59:33,679] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:59:33,679] I Program end
[2017-12-04 15:59:36,358] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:59:36,358] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:59:36,359] I Program end
[2017-12-04 15:59:59,842] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 15:59:59,843] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 15:59:59,843] I Program end
[2017-12-04 16:00:00,674] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:00:00,674] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:00:00,674] I Program end
[2017-12-04 16:37:42,965] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:37:42,966] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:37:42,967] I Program end
[2017-12-04 16:37:44,420] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:37:44,421] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:37:44,421] I Program end
[2017-12-04 16:37:45,553] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:37:45,553] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:37:45,553] I Program end
[2017-12-04 16:38:10,081] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:10,081] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:10,081] I Program end
[2017-12-04 16:38:11,474] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:11,474] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:11,474] I Program end
[2017-12-04 16:38:12,470] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:12,471] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:12,471] I Program end
[2017-12-04 16:38:24,291] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:24,291] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:24,291] I Program end
[2017-12-04 16:38:34,918] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:34,918] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:34,919] I Program end
[2017-12-04 16:38:36,826] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:36,826] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:36,826] I Program end
[2017-12-04 16:38:38,583] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:38,583] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:38:38,583] I Program end
[2017-12-04 16:38:55,448] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:55,449] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:38:56,704] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:56,704] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:38:57,262] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:57,262] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:38:58,755] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:38:58,755] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:39:10,711] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:10,712] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0) is not None:
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:39:11,566] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:11,566] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0) is not None:
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:39:19,998] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:19,999] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0) is not None:
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:39:21,034] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:21,035] E 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "log_analyzer.py", line 195, in <module>
    main()
  File "log_analyzer.py", line 178, in main
    log_file_path = find_last_log_file_path(conf)
  File "log_analyzer.py", line 85, in find_last_log_file_path
    if pr.group(0) is not None:
AttributeError: 'NoneType' object has no attribute 'group'
[2017-12-04 16:39:35,215] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:35,216] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:39:35,216] I Program end
[2017-12-04 16:39:37,612] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:39:37,612] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:39:37,613] I Program end
[2017-12-04 16:41:04,030] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:41:04,033] I Program end
[2017-12-04 16:41:05,456] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:41:05,457] I ./log/nginx-access-ui.log-201706303 log was previously processed
[2017-12-04 16:41:05,457] I Program end
[2017-12-04 16:41:22,683] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:41:22,684] I ./log/nginx-access-ui.log-201706303 log was previously processed
[2017-12-04 16:41:22,684] I Program end
[2017-12-04 16:41:35,260] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:41:35,260] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:41:35,260] I Program end
[2017-12-04 16:41:55,913] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:41:55,914] I Program end
[2017-12-04 16:46:24,219] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:46:24,220] I ./log/nginx-access-ui.log-20170630defef log was previously processed
[2017-12-04 16:46:24,220] I Program end
[2017-12-04 16:48:05,534] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 16:48:05,535] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 16:48:05,535] I Program end
[2017-12-04 17:06:02,746] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:06:21,632] I Program end
[2017-12-04 17:06:45,109] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:06:45,110] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:06:45,110] I Program end
[2017-12-04 17:09:32,728] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:09:32,728] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:09:32,728] I Program end
[2017-12-04 17:14:34,682] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:14:34,683] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:14:34,683] I Program end
[2017-12-04 17:17:52,087] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:17:52,087] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:17:52,087] I Program end
[2017-12-04 17:38:15,071] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:38:15,072] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:38:15,072] I Program end
[2017-12-04 17:38:27,462] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:38:46,339] I Program end
[2017-12-04 17:38:53,524] I Start program with config {'REPORT_DIR': './reports', 'MONITOR_LOG': 'monitor_log.log', 'LOG_DIR': './log', 'TS_FILE_PATH': '/var/tmp/log_analyzer.ts', 'URL_POS': 7, 'REPORT_SIZE': 1000, 'CONFIG_DEFAULT_PATH': '/usr/local/etc/log_analyzer.conf', 'REQUEST_TIME_POS': -1}
[2017-12-04 17:38:53,525] I ./log/nginx-access-ui.log-20170630.gz log was previously processed
[2017-12-04 17:38:53,525] I Program end
